# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

['aamuirc',
'Anime-Chat',
'Aniverse',
'Blitzed',
'B2IRC',
'Chatsociety',
'CyberArmy',
'DALnet',
'DarkMyst',
'EFNet',
'EnterTheGame',
'EQUNet',
'EsperNet',
'ffffans.net',
'FinIRCnet',
'FooLink',
'freenode',
'GamesNET',
'GameSurge',
'GIMPnet',
'IhmeNet',
'IRCFutureNet',
'IRCHighWay',
'IRCnet',
'IrcWorld',
'irc6',
'JPXnet',
'linknet',
'Lysti.net',
'NetGamers',
'NetGames.fi',
'OFTC',
'Partynet',
'QuakeNet',
'SceNet',
'SorceryNet',
'Stratics',
'SwipeNet',
'TheOneRing.net',
'TitanixNET',
'Undernet',
'Coldfront'].each do |name|
  Network.create!(:name => name)
end